### ISSUE TITLE
大佬我跑不起来 一直说是数据源有问题

### ISSUE THREAD

**Issue by Xuer123** [m1176873550/landry-system#1]
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.        

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
        If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
        If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
```
## 下面是我的配置
```yml

spring:
  #数据库配置
  datasource:
    name: laundry
    url: jdbc:mysql://43.140.245.94:3306/laundry?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: ****
    password: ******
    #druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
```
